export const FETCH_RANDOM_WORD = 'GET_RANDOM_WORD';
export const CORRECT_USER_GUESS = 'CORRECT_USER_GUESS';
export const INCORRECT_USER_GUESS = 'INCORRECT_USER_GUESS';
export const RESET_GAME = 'RESET_GAME';
export const GAME_STARTED = 'GAME_STARTED';